
const DUMMY_COURSES =[
    {
      id:1,
      category:"PYTHON",
      title:"Python for Everybody",
      image:"https://seekify-public.s3.ap-south-1.amazonaws.com/seekify-file-image%252Fwebp-1672654771476-Python%20for%20Everybody%21.webp",
      description:"This Specialization builds on the success of the Python for Everybody course and will introduce fundamental programming concepts including data structures, networked application program interfaces, and databases, using the Python programming language. In the Capstone Project, youll use the technologies learned throughout the Specialization to design and create your own  applications for data retrieval, processing, and visualization.",    
      src:'https://youtube.com/embed/vLqTf2b6GZw' ,
      content1:"Programming for Everybody (Getting Started with Python)",
      content2:"Python Data Structures",
      content3:"Using Python to Access Web Data",
      content4:"Using Databases with Python",
      content5:"Capstone: Retrieving, Processing, and Visualizing Data with Python",
      inner1:"Python Install",
      inner2:"Python Quickstart",
      inner3:"Hello World!",
      inner4:"The Python Command Line",
      inner5:"Arrays",
      inner6:"Lists",
      inner7:"Tuples",
      inner8:"Dictionaries",
      inner9:"API's",
      inner10:"Different HTTP Methods and Status Codes",
      inner11:"API Endpoints",
      inner12:"CRUD Operations",
      inner13:"Python MySQL",
      inner14:"Python SQLite",
      inner15:"Python JSON",
      inner16:"Python MongoDB",
        },
    {
      id:2,
      title:"Crash Course on Python",
      category:"PYTHON",
      image:"https://images.hdqwalls.com/wallpapers/python-logo-4k-i6.jpg",
      description:"This course is designed to teach you the foundations in order to write simple programs in Python using the most common structures. No previous exposure to programming is needed. By the end of this course, you'll understand the benefits of programming in IT roles; be able to write simple programs using Python; figure out how the building blocks of programming fit together; and combine all of this knowledge to solve a complex programming problem.",
      src:'https://youtube.com/embed/_uQrJ0TkZlc' ,
      content1:"Hello Python!",
      content2:"Basic Python Syntax",
      content3:"Loops",
      content4:"Strings, Lists and Dictionaries",
      content5:"",
      inner1:"What is Python?",
      inner2:"Why is Python relevant to IT?",
      inner3:"Hello, World!",
      inner4:"Getting Information from the User",
      inner5:"Data Types, Variables",
      inner6:"Expressions, Numbers, and Type Conversions",
      inner7:"Defining Functions",
      inner8:"Control Statements",
      inner9:"Introduction to Loops",
      inner10:"Infinite Loops and How to Break Them",
      inner11:"Nested for Loops",
      inner12:"What is recursion?",
      inner13:"Creating New Strings",
      inner14:"Formatting Strings",
      inner15:"Lists and Tuples",
      inner16:"Dictionaries vs. Lists"

    },
    {
      id:3,
      title:"Python for Data Science, AI & Development",
      category:"PYTHON",
      image:"https://hopetutors.com/wp-content/uploads/2019/06/Python-for-Data-Science-1.jpg",
      description:"Kickstart your learning of Python with this beginner-friendly self-paced course taught by an expert. Python is one of the most popular languages in the programming and data science world and demand for individuals who have the ability to apply Python has never been higher.This introduction to Python course will take you from zero to programming in Python in a matter of hours—no prior programming experience necessary! You will learn about Python basics and the different data types. You will familiarize yourself with Python Data structures like List and Tuples, as well as logic concepts like conditions and branching. You will use Python libraries such as Pandas, Numpy & Beautiful Soup. You’ll also use Python to perform tasks such as data collection and web scraping with APIs.",    
      src:'https://youtube.com/embed/LHBE6Q9XlzI' ,
      content1:"Python Basics",
      content2:"Python Data Structures",
      content3:"Python Programming Fundamentals",
      content4:"Working with Data in Python",
      inner1:"Introduction",
      inner2:"Types",
      inner3:"Expressions and Variables",
      inner4:"String Operations",
      inner5:"Data Structures USed",
      inner6:"List and Tuples",
      inner7:"Dictionaries",
      inner8:"Sets",
      inner9:"Conditions and Branching",
      inner10:"Loops, Functions",
      inner11:"Exception Handling",
      inner12:"Objects and Classes",
      inner13:"Reading and Writing Files with Open",
      inner14:"Loading Data with Pandas and Working, Saving Data",
      inner15:"One Dimensional Numpy",
      inner16:"Two Dimensional Numpy",
    },
    {
      id:4,
      title:"Introduction to Java",
      category:"JAVA",
      image:'https://miro.medium.com/v2/resize:fit:1400/1*qMOFlwg2jiatIqUqH4h11Q.jpeg',
      description:"This Course is the first of a series of courses that make up the Core Java Specialization.  The Core Java Specialization, in turn, is part of a series of programming specializations, derived from LearnQuest's private Java Bootcamps, designed to provide the skill set necessary to be hired as an IT developer using Java in many corporate environments.This course includes hands-on practice and will give you a solid knowledge of the Java language. After completing this course, you will be able to identify Javas benefits, program in basic Java syntax using Java data types, and incorporate branches and loops.", 
      src:'https://youtube.com/embed/eIrMbAQSU34' ,
      content1:"Introduction to Java",
      content2:"Java Language Fundamentals - Types",
      content3:"Java Language Fundamentals - Flow of Control",
      content4:"Memory Allocation in Java",
      inner1:"Module Introduction and Benefits of Java",
      inner2:"Key Benefits: Packages, Syntax and Libraries",
      inner3:"Key Benefits: Connectivity and Performance",
      inner4:"Java Product Suite, Java Standard Edition(SE), Java Enterprise Edition (EE),Java Micro Edition (ME) ",
      inner5:"Java Types - Syntax",
      inner6:"Primitive Data Types, Creating Primitives",
      inner7:"Wrapper Classes",
      inner8:"Arrays",
      inner9:"Java Operators",
      inner10:"If, Else Statements",
      inner11:"While,for Loop",
      inner12:"Break and Continue Statements",
      inner13:"Java Memory Management",
      inner14:"Stack vs Heap Memory Allocation",
      inner15:"Garbage Collection",
      inner16:"Memory leaks in Java",
    },
    {
      id:5,
      title:"Object Oriented Programming in Java Specialization",
      category:"JAVA",
      image:'https://1.bp.blogspot.com/-GRNuxO0n9ys/YG_wiYUHCnI/AAAAAAAAbh0/ZciwwXqrm_sLU3fMhLHz_HgFwa0oKG_dgCNcBGAsYHQ/s577/oops-IN-JAVA.png',
      description:"This Specialization is for aspiring software developers with some programming experience in at least one other programming language (e.g., Python, C, JavaScript, etc.) who want to be able to solve more complex problems through objected-oriented design with Java. In addition to learning Java, you will gain experience with two Java development environments (BlueJ and Eclipse), learn how to program with graphical user interfaces, and learn how to design programs capable of managing large amounts of data. These software engineering skills are broadly applicable across wide array of industries.",
      src:'https://youtube.com/embed/6T_HgnjoYwM' ,
      content1:"Java Programming: Solving Problems with Software",
      content2:"Java Programming: Arrays, Lists, and Structured Data",
      content3:"Object Oriented Programming in Java",
      content4:"Data Structures and Performance",
      inner1:"Learn to code in Java and improve your programming and problem-solving skills. You will learn to design algorithms as well as develop and debug programs. Using custom open-source classes, you will write programs that access and transform images, websites, and other types of data. At the end of the course you will build a program that determines the popularity of different baby names in the US over time by analyzing comma separated value (CSV) files. ",
      inner5:"Build on the software engineering skills you learned in “Java Programming: Solving Problems with Software” by learning new data structures. Use these data structures to build more complex programs that use Java’s object-oriented features. At the end of the course you will write an encryption program and a program to break your encryption algorithm.",
      inner9:"Our goal is that by the end of this course each and every one of you feels empowered to create a Java program that’s more advanced than any you have created in the past and that is personally interesting to you. In achieving this goal you will also learn the fundamentals of Object Oriented Programming, how to leverage the power of existing libraries, how to build graphical user interfaces, and how to use some core algorithms for searching and sorting data. And this course is project-based, so we’ll dive right into the project immediately!",
      inner13:"How do Java programs deal with vast quantities of data? Many of the data structures and algorithms that work with introductory toy examples break when applications process real, large data sets.  Efficiency is critical, but how do we achieve it, and how do we even measure it? This is an intermediate Java course. We recommend this course to learners who have previous experience in software development or a background in computer science, and in particular, we recommend that you have taken the first course in this specialization (which also requires some previous experience with Java).  ",
      inner2:"Develop a set of test cases as part of developing a programs",
      inner6:"Store and manipulate data in an array or ArrayList",
      inner7:"Use iterables and collections (including maps) in Java.",
      inner8:"Solve problems involving data files",
      inner3:"Create a class with multiple methods that work together to solve a problem",
      inner10:"We are excited to be offering a unique course structure, designed to support learners of different backgrounds in succeeding at their own pace. The first module explains how this will work and if this course is right for you. ",
      inner11:" We also recommend taking a few minutes to explore the course site. A good place to start is the navigation bar on the left. Click Course Content to see what material we’ll cover each week, as well preview the assignments you’ll need to complete to pass the course. Click Discussions to see forums where you can discuss the course material with fellow students taking the class. Be sure to introduce yourself to everyone in the Meet and Greet forum.",
      inner12:"This course should take about 6 weeks to complete. You can check out the recommended course schedule below to see a quick overview of the lessons and assignments you’ll complete each week.",
      inner4:"Use Java API documentation in writing programs.",
      inner14:"How do Java programs deal with vast quantities of data? Many of the data structures and algorithms that work with introductory toy examples break when applications process real, large data sets.  Efficiency is critical, but how do we achieve it, and how do we even measure it?",
      inner15:"This is an intermediate Java course. We recommend this course to learners who have previous experience in software development or a background in computer science, and in particular, we recommend that you have taken the first course in this specialization (which also requires some previous experience with Java).",
      inner16:"The program you will build throughout this course allows its user to manage, manipulate and reason about large sets of textual data.  This is an intermediate Java course, and we will build on your prior knowledge.  This course is designed around  the same video series as in our first course in this specialization, including explanations of core content, learner videos, student and engineer testimonials, and support videos -- to better allow you to choose your own path through the course!",
    },
    {
      id:6,
      title:"Java Programming and Software Engineering Fundamentals Specialization",
      category:"JAVA",
      image:'https://media.licdn.com/dms/image/C5612AQGYe2V_dZL3zw/article-cover_image-shrink_600_2000/0/1583274093371?e=2147483647&v=beta&t=Rgx-Tq-V1r0gOKBZcUxY9nTGObvbr_ooowQeOazl51I',
      description:"Take your first step towards a career in software development with this introduction to Java—one of the most in-demand programming languages and the foundation of the Android operating system. Designed for beginners, this Specialization will teach you core programming concepts and equip you to write programs to solve complex problems. In addition, you will gain the foundational skills a software engineer needs to solve real-world problems, from designing algorithms to testing and debugging your programs.",    
      src:'https://youtube.com/embed/d2b-JONFPzA' ,
      content1:"Programming Foundations with JavaScript, HTML and CSS",
      content2:"Java Programming: Solving Problems with Software",
      content3:"Java Programming: Arrays, Lists, and Structured Data",
      content4:"Java Programming: Principles of Software Design",
      inner1:"Learn foundational programming concepts (e.g., functions, for loops, conditional statements) and how to solve problems like a programmer. In addition, learn basic web development as you build web pages using HTML, CSS, JavaScript. By the end of the course, will create a web page where others can upload their images and apply image filters that you create.",
      inner5:"Learn to code in Java and improve your programming and problem-solving skills. You will learn to design algorithms as well as develop and debug programs. Using custom open-source classes, you will write programs that access and transform images, websites, and other types of data. At the end of the course you will build a program that determines the popularity of different baby names in the US over time by analyzing comma separated value (CSV) files. ",
      inner9:"Build on the software engineering skills you learned in “Java Programming: Solving Problems with Software” by learning new data structures. Use these data structures to build more complex programs that use Java’s object-oriented features. At the end of the course you will write an encryption program and a program to break your encryption algorithm.After completing this course, you will be able to:",
      inner13:"Solve real world problems with Java using multiple classes. Learn how to create programming solutions that scale using Java interfaces. Recognize that software engineering is more than writing code - it also involves logical thinking and design. By the end of this course you will have written a program that analyzes and sorts earthquake data, and developed a predictive text generator.",
      inner10:" Read and write data from/to files",
      inner2:"Write JavaScript programs using functions, for loops, and conditional statements",
      inner3:"Use HTML to construct a web page with paragraphs, divs, images, links, and lists;",
      inner4:"Make a web page interactive with JavaScript commands like alert, onClick, onChange, adding input features like an image canvas, button, and slider.",
      inner11:"Perform quantitative analyses of data (e.g., finding maximums, minimums, averages)",
      inner12:"Combine multiple classes to solve larger problems",
      inner6:"Use conditionals and loops in a Java program",
      inner7:"Use Java API documentation in writing programs.",
      inner8:"Use divide-and-conquer design techniques for a program that uses multiple methods.",
      inner14:"Determine if a class from the Java API can be used in solving a particular problem",
      inner15:"Use object-oriented concepts including interfaces and abstract classes when developing programs",
      inner16:"Recognize standard Java classes and idioms including exception-handling, static methods, java.net, and java.io packages.",
    },
    {
      id:7,
      title:"Introduction to Artificial Intelligence (AI)",
      category:"AI",
      image:'https://a4arch.com/wp-content/uploads/2023/02/Featured-image-Augmented-Intelligence.jpg',
      description:"In this course you will learn what Artificial Intelligence (AI) is, explore use cases and applications of AI, understand AI concepts and terms like machine learning, deep learning and neural networks. You will be exposed to various issues and concerns surrounding AI such as ethics and bias, & jobs, and get advice from experts about learning and starting a career in AI.  You will also demonstrate AI in action with a mini project.This course does not require any programming or computer science expertise and is designed to introduce the basics of AI to anyone whether you have a technical background or not.",    
      src:'https://youtube.com/embed/JMUxmLyrhSk' ,
      content1:"What is AI? Applications and Examples of AI",
      content2:"AI Concepts, Terminology, and Application Areas",
      content3:"AI: Issues, Concerns and Ethical Considerations",
      content4:"The Future with AI, and AI in Action",
      inner1:"What is AI?",
      inner2:"Optional: Tanmay’s journey and take on AI",
      inner3:"Impact and Examples of AI",
      inner4:"Some Applications of AI",
      inner5:"Cognitive Computing (Perception, Learning, Reasoning)",
      inner6:"Machine Learning Techniques and Training",
      inner7:"Deep Learning",
      inner8:"Natural Language Processing, Speech, Computer Vision",
      inner9:"Exploring Today's AI Concerns",
      inner10:"Defining AI Ethics",
      inner11:"Understanding Bias and AI",
      inner12:"AI Ethics, Governance, and ESG",
      inner13:"The evolution and future of AI",
      inner14:"The AI Ladder - The Journey for Adopting AI Successfully",
      inner15:"Advice for a career in AI",
      inner16:"Hotbeds of AI Innovation",

    },
    {
      id:8,
      title:"Machine Learning Specialization",
      category:"AI",
      image:'https://media.istockphoto.com/id/966248982/photo/robot-with-education-hud.jpg?s=612x612&w=0&k=20&c=9eoZYRXNZsuU3edU87PksxN4Us-c9rB6IR7U_IGZ-U8=',
      description:"It provides a broad introduction to modern machine learning, including supervised learning (multiple linear regression, logistic regression, neural networks, and decision trees), unsupervised learning (clustering, dimensionality reduction, recommender systems), and some of the best practices used in Silicon Valley for artificial intelligence and machine learning innovation (evaluating and tuning models, taking a data-centric approach to improving performance, and more.)",   
      src:'https://youtube.com/embed/GwIo3gDZCVQ' ,
      content1:"Supervised Machine Learning: Regression and Classification",
      content2:"Advanced Learning Algorithms",
      content3:"Unsupervised Learning, Recommenders, Reinforcement Learning",
      content4:"Regression",
      inner1:"In the first course of the Machine Learning Specialization, you will:",
      inner2:"Build machine learning models in Python using popular machine learning libraries NumPy and scikit-learn.",
      inner3:"Build and train supervised machine learning models for prediction and binary classification tasks, including linear regression and logistic regression",
      inner4:"The Machine Learning Specialization is a foundational online program created in collaboration between DeepLearning.AI and Stanford Online. In this beginner-friendly program, you will learn the fundamentals of machine learning and how to use these techniques to build real-world AI applications.",
      inner5:"In the second course of the Machine Learning Specialization, you will:",
      inner6:"Build and train a neural network with TensorFlow to perform multi-class classification",
      inner7:"Apply best practices for machine learning development so that your models generalize to data and tasks in the real world.",
      inner8:"Build and use decision trees and tree ensemble methods, including random forests and boosted trees",
      inner9:"In the third course of the Machine Learning Specialization, you will: ",
      inner10:"Use unsupervised learning techniques for unsupervised learning: including clustering and anomaly detection.",
      inner11:"Build recommender systems with a collaborative filtering approach and a content-based deep learning method.",
      inner12:"Build a deep reinforcement learning model.",
      inner13:"Supoort Vector Regression",
      inner14:"Decision Tree Regression",
      inner15:"Simple Linear Regression",
      inner16:"Multiple Linear Regression",

    },
    {
      id:9,
      title:"AI For Everyone",
      category:"AI",
      image:'https://thumbs.dreamstime.com/b/ai-artificial-intelligence-machine-learning-big-data-analysis-automation-technology-business-industrial-manufacturing-132528154.jpg',
      description:"AI is not only for engineers. If you want your organization to become better at using AI, this is the course to tell everyone--especially your non-technical colleagues--to take. ",    
      src:'https://youtube.com/embed/gD_HWj_hvbo?list=PLGs0VKk2DiYyXlbJVaE8y1qr24YldYNDm' ,
      content1:"What is AI?",
      content2:"Building AI Projects",
      content3:"Building AI in Your Company",
      content4:"AI and Society",
      inner1:"What is data?",
      inner2:"The terminology of AI",
      inner3:"What makes an AI company?",
      inner4:"More examples of what machine learning can and cannot do",
      inner5:"Workflow of a machine learning project",
      inner6:"Every job function needs to learn how to use data",
      inner7:"How to choose an AI project (Part 1)",
      inner8:"How to choose an AI project (Part 2)",
      inner9:"Case study: Self-driving car",
      inner10:"Example roles of an AI team",
      inner11:"AI Transformation Playbook (Part 1)",
      inner12:"AI Transformation Playbook (Part 2)",
      inner13:"A realistic view of AI",
      inner14:"Discrimination / Bias",
      inner15:"Adverse uses and attacks of AI",
      inner16:"AI and jobs",

    },
    {
      id:10,
      title:"MERN Stack Front To Back: Full Stack React, Redux & Node.js",
      category:'MERN',
      image:'https://wallpaperaccess.com/full/8901670.png',




      src:'https://youtube.com/embed/ktjafK4SgWM' ,
      content1:"MongoDB",
      content2:"ExpressJS",
      content3:"React",
      content4:"Node JS",
      inner1:"Getting Started and Database Creation",
      inner2:"Operations on Database and Collections",
      inner3:"MongoDB Validation",
      inner4:"MongoDB Data API",
      inner5:"HTTP Methods",
      inner6:"Middleware",
      inner7:"URL Binding",
      inner8:"Cookies",
      inner9:"Components",
      inner10:"Props",
      inner11:"Events",
      inner12:"React Router",
      inner13:"File System",
      inner14:"URL Module",
      inner15:"NPM",
      inner16:"Events",
    },
    {
      id:11,
      category:'popular',
      title:'Learn Guitar The Easy Wayy',
      image:'https://play-guitars.com/wp-content/uploads/2019/06/the-top-6-techniques-for-practising-acoustic-guitar-01-1.jpg',
      description:'Step by step guitar course. 5 minute lessons. Learn to play chords, melodies, warm up exercises, music theory...',
      src:'https://youtube.com/embed/QS0VjFm_65E' ,
      content1:'Scales:Chromatic, G, D And F Major',
      content2:'Tuning guitar, first chords and rhythms',
      content3:'First Lesson On Music Theory, LH Techniques',
      content4:'Chords And Degrees Of The Scale,Bass Lines',
      inner1:'Warm-Up: C Major Chord',
      inner2:'Warm-Up: C Minor Chord',
      inner3:'First Waltz: 3/4, C Major and A Minor Chords',
      inner4:'Major and Minor: Exercising Chords',
      inner5:'First Bite of Music Theory',
      inner6:'Dancing On The Stairs',
      inner7:'In the Garder: Melody, Chords, Rhythm',
      inner8:'C and F Major, Right Hand Techniques',
      inner9:'Second Bite Of Music Theory - Chords In C Major Scale',
      inner10:'By The Sea Part 1: Melody, Chords',
      inner11:'Small Bite Of Music Theory - Bass Lines',
      inner12:'Multitasking: Chords + Bass Line',
      inner13:'Third Bite Of Music Theory: Chromatic Scale',
      inner14:'Walking Part 1: Chords and Rhythm, Melody',
      inner15:'D Major Scales',
      inner16:'F Major Scales',
    },
    {
      id:12,
      category:'popular',
      title:'Complete PHP Bootcamp',
      image:'https://www.netsolutions.com/insights/wp-content/uploads/2022/11/what-is-php-for-web-development-and-reason-to-use-it.png',
      description:'Learn to build websites with HTML , CSS , JAVASCRIPT , Bootstrap , PHP , MySQL , WordPress , OOP & more!',
      src:'https://youtube.com/embed/6EukZDFE_Zg' ,
      content1:'Introduction to HTML 5',
      content2:'Introduction to CSS3',
      content3:'HTML+CSS3 Projects',
      content4:'Introduction to JavaScript',
      inner1:'Header Tags, Paragraphs and Comments',
      inner2:'Link Tags, Section And Articles',
      inner3:'Tables, Embedding Contents, Lists',
      inner4:'Forms, DIV And SPAN Tags',
      inner5:'Inline CSS, External CSS, Internal CSS',
      inner6:'CSS Selectors, Psuedo Class and Elements',
      inner7:'Positioning Elements',
      inner8:'Project: Website Layout',
      inner9:'Product Landing Page',
      inner10:'Survey Page',
      inner11:'Google Home Page',
      inner12:'Your Personal Website',
      inner13:'Internal JS, Inline JS, Comments',
      inner14:'Identifiers, Variables, Constants, Primitives, Keywords, Operators',
      inner15:'Quotes, Boolean,Arrays',
      inner16:'Date,Time And Control Statements',
    },
    {
      id:13,
      category:'popular',
      title:'Learn Python A-Z',
      image:'https://www.digitalnest.in/blog/wp-content/uploads/2019/07/10-Benefits-of-Learning-Python-Programming-Language-and-Its-Use-Cases.png',
      description:"This Specialization builds on the success of the Python for Everybody course and will introduce fundamental programming concepts including data structures, networked application program interfaces, and databases, using the Python programming language. In the Capstone Project, youll use the technologies learned throughout the Specialization to design and create your own  applications for data retrieval, processing, and visualization.",    
      src:'https://youtube.com/embed/ITSMDeOgXxw' ,
      content1:"Hello Python!",
      content2:"Basic Python Syntax",
      content3:"Loops",
      content4:"Strings, Lists and Dictionaries",
      content5:"",
      inner1:"What is Python?",
      inner2:"Why is Python relevant to IT?",
      inner3:"Hello, World!",
      inner4:"Getting Information from the User",
      inner5:"Data Types, Variables",
      inner6:"Expressions, Numbers, and Type Conversions",
      inner7:"Defining Functions",
      inner8:"Control Statements",
      inner9:"Introduction to Loops",
      inner10:"Infinite Loops and How to Break Them",
      inner11:"Nested for Loops",
      inner12:"What is recursion?",
      inner13:"Creating New Strings",
      inner14:"Formatting Strings",
      inner15:"Lists and Tuples",
      inner16:"Dictionaries vs. Lists"
    }, {
      id:14,
      category:'popular',
      title:'Hands-on Artificial Intelligence',
      image:'https://www.zdnet.com/a/img/resize/1b0f3a471607ff123236026b04b964e1853ed41b/2023/04/05/e0478a88-b3ed-4516-8459-e0b919b4b2bc/artificial-intelligence.jpg?auto=webp&fit=crop&height=900&width=1200',
      description:"In this course you will learn what Artificial Intelligence (AI) is, explore use cases and applications of AI, understand AI concepts and terms like machine learning, deep learning and neural networks. You will be exposed to various issues and concerns surrounding AI such as ethics and bias, & jobs, and get advice from experts about learning and starting a career in AI.  You will also demonstrate AI in action with a mini project.This course does not require any programming or computer science expertise and is designed to introduce the basics of AI to anyone whether you have a technical background or not.",    
      src:'https://youtube.com/embed/VOaoabf3LPM' ,
      content1:"What is AI? Applications and Examples of AI",
      content2:"AI Concepts, Terminology, and Application Areas",
      content3:"AI: Issues, Concerns and Ethical Considerations",
      content4:"The Future with AI, and AI in Action",
      inner1:"What is AI?",
      inner2:"Optional: Tanmay’s journey and take on AI",
      inner3:"Impact and Examples of AI",
      inner4:"Some Applications of AI",
      inner5:"Cognitive Computing (Perception, Learning, Reasoning)",
      inner6:"Machine Learning Techniques and Training",
      inner7:"Deep Learning",
      inner8:"Natural Language Processing, Speech, Computer Vision",
      inner9:"Exploring Today's AI Concerns",
      inner10:"Defining AI Ethics",
      inner11:"Understanding Bias and AI",
      inner12:"AI Ethics, Governance, and ESG",
      inner13:"The evolution and future of AI",
      inner14:"The AI Ladder - The Journey for Adopting AI Successfully",
      inner15:"Advice for a career in AI",
      inner16:"Hotbeds of AI Innovation",
    },
    {
      id:15,
      category:'popular',
      title:'Learn Vue JS',
      image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEZpuKKtaZnmLwSsbp6XAHwTr-ThSUMUaGThxDFug0RA&usqp=CAU&ec=48665699',
      description:'Learn how to make front-end web apps with ease using Vue.js, an increasingly popular JavaScript front-end framework.',
      src:'https://youtube.com/embed/0xt_Jv-P_Vo' ,
      content1:'Intoduction to Vue',
      content2:'Data Binding And Event Handling',
      content3:'Transitions in Vue JS',
      content4:'Animation in Vue JS',
      inner1:'Installation',
      inner2:'Declarative Rendering And Conditions & Loops',
      inner3:'Vue.js Instances And Components',
      inner4:'Computed Properties',
      inner5:'Vue.js Data Binding',
      inner6:'Form Input Bindings',
      inner7:'Vue.js Watch Property',
      inner8:'Vue.js Event Handling',
      inner9:'What is Transition',
      inner10:'Vue.js Transition',
      inner11:'Explicit Transition',
      inner12:'Vue.js Custom Directives',
      inner13:'What is Animation',
      inner14:'Vue.js Animation',
      inner15:'vue.js Routing and Mixins',
      inner16:'Vue.js Reactivity System',
    },
    {
      id:16,
      category:'popular',
      title:'Angular JS',
      image:'https://www.etatvasoft.com/blog/wp-content/uploads/2017/01/b-thumb-img12.jpg',
      description:'The most comprehensive Angular 4 (Angular 2+) course. Build a real e-commerce app with Angular, Firebase and Bootstrap 4',
      src:'https://youtube.com/embed/3qBXWUpoPHo' ,
      content1:'TypeScript And Angular Fundamentals',
      content2:'Displaying Data and Handling Events, Building Re-usable Components',
      content3:'Directives, Template-driven Forms, Reactive Forms',
      content4:'Consuming HTTP Services And Routing & Navigation',
      inner1:'Types,Type Assertions, Arrow Functions,Interfaces,Classes',
      inner2:'Objects,Constructors, Access Modifiers, Modules',
      inner3:'Building Blocks of Angular Apps, Components',
      inner4:'Templates, Directives, Services, Dependency Injection',
      inner5:'Property, Attribute Binding',
      inner6:'Class, Style, Event, Binding and Event Filtering, Pipes',
      inner7:'Input Properties Aliasing, Output Properties Aliasing, Templates',
      inner8:'Styles, View Encapsulation, ngContent, ngContainer',
      inner9:'ngIf, ngSwitchCase, ngFor, ngClass',
      inner10:'ngModel, ngForm, ngModelGroup',
      inner11:'Adding Validation, Asunchronous Operations and Validators',
      inner12:'Specific Validation Errors, FormArray, FormBuilder',
      inner13:'JSONPlaceHolder, CRUD Operations',
      inner14:'Handling Errors, Bad Request Errors',
      inner15:'Global Error Handling, The Map Operator',
      inner16:'RouterOutlet, RouterLink, RouterLinkActive',
    },
    {
      id:17,
      category:'popular',
      title:'JavaScript Course',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/800px-JavaScript-logo.png',
      description:'Learn JavaScript Learn how to use JavaScript — a powerful and flexible programming language for adding website interactivity.',
      src:'https://youtube.com/embed/SBmSRK3feww' ,
      content1:'JavaScript Fundamentals',
      content2:'JavaScript in the Browser:DOM and Events Fundamentals',
      content3:'How JavaScript Works Behind The Scenes',
      content4:'Data Structures, Modern Operators and Strings',
      inner1:'Values and Variables, let, const and var , Operators',
      inner2:'Equality Operators: == vs. ===, The Switch Statement , Expressions ',
      inner3:'Functions, Arrow Functions, Reviewing Functions',
      inner4:'Introduction to Objects, Dot vs. Bracket Notation',
      inner5:'Whats the DOM and DOM Manipulation',
      inner6:'Selecting and Manipulating Elements',
      inner7:'Coding Challenge!',
      inner8:'Refactoring Our Code: The DRY Principle',
      inner9:'The JavaScript Engine and Runtime',
      inner10:'Variable Environment: Hoisting and The TDZ',
      inner11:'Regular Functions vs. Arrow Functions',
      inner12:'Primitives vs. Objects (Primitive vs. Reference Types)',
      inner13:'Destructuring Arrays and Objects',
      inner14:'The Spread Operator (...), Rest Pattern and Parameters',
      inner15:'Short Circuiting (&& and ||), The Nullish Coalescing Operator (??)',
      inner16:'Enhanced Object Literals, Optional Chaining (?.)',
    },
    {
      id:18,
      category:'popular',
      title:'MERN Full Stack',
      image:'https://miro.medium.com/v2/resize:fit:678/0*kxPYwfJmkXZ3iCWy.png',
      description:"Build and deploy a social network with Node.js, Express, React, Redux & MongoDB. Fully updated April 2019",   
      src:'https://youtube.com/embed/ZxKM3DCV2kE' ,
      content1:"MongoDB",
      content2:"ExpressJS",
      content3:"React",
      content4:"Node JS",
      inner1:"Getting Started and Database Creation",
      inner2:"Operations on Database and Collections",
      inner3:"MongoDB Validation",
      inner4:"MongoDB Data API",
      inner5:"HTTP Methods",
      inner6:"Middleware",
      inner7:"URL Binding",
      inner8:"Cookies",
      inner9:"Components",
      inner10:"Props",
      inner11:"Events",
      inner12:"React Router",
      inner13:"File System",
      inner14:"URL Module",
      inner15:"NPM",
      inner16:"Events",
    },
    {
      id:19,
      category:'popular',
      title:'JAVA',
      image:'https://codemithra.com/wp-content/uploads/2020/06/java-logo.png',
      description:'This course includes hands-on practice and will give you a solid knowledge of the Java language. After completing this course, you will be able to identify Java’s benefits, program in basic Java syntax using Java data types, and incorporate branches and loops.',
      src:'https://youtube.com/embed/CFD9EFcNZTQ' ,
      content1:"Introduction to Java",
      content2:"Java Language Fundamentals - Types",
      content3:"Java Language Fundamentals - Flow of Control",
      content4:"Memory Allocation in Java",
      inner1:"Module Introduction and Benefits of Java",
      inner2:"Key Benefits: Packages, Syntax and Libraries",
      inner3:"Key Benefits: Connectivity and Performance",
      inner4:"Java Product Suite, Java Standard Edition(SE), Java Enterprise Edition (EE),Java Micro Edition (ME) ",
      inner5:"Java Types - Syntax",
      inner6:"Primitive Data Types, Creating Primitives",
      inner7:"Wrapper Classes",
      inner8:"Arrays",
      inner9:"Java Operators",
      inner10:"If, Else Statements",
      inner11:"While,for Loop",
      inner12:"Break and Continue Statements",
      inner13:"Java Memory Management",
      inner14:"Stack vs Heap Memory Allocation",
      inner15:"Garbage Collection",
      inner16:"Memory leaks in Java",
    }
    
  ]
  export default DUMMY_COURSES;